fixtures:
  forge_modules:
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "3.0.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref: "3.0.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.2.2"
    apache:
      repo: "puppetlabs/apache"
      ref: "1.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.1.1"
    apt: "puppetlabs/apt"
  symlinks:
    puppet: "#{source_dir}"
